name: Backend Actions
on:
  push:
    paths:
      - "backend/**"
      - "!frontend/**"
      - "!bot/**"
  pull_request:
    branches:
      - main
      - dev
defaults:
  run:
    working-directory: backend
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "adopt"
      - run: |
          mvn formatter:validate --no-transfer-progress

  # TODO: build and test jobs for dev/main, deploy for main
  # TODO: set up docker container pre-loaded with requirements?
